views:
  ressource: '../views'
  extension: 'sonata'

routes:
  private:
    - '^/'
    - '^/admin'
    - '^/admin/login/'
    - '^/admin/logout'
  public:
    - '^/'
    - '^/login'
    - '^/logout'
